version: '3.1'

services:
  # db:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   expose:
  #     - 27017
  #   environment: 
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: test

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: imessage
